travis:
  secure:
    BINSTAR_TOKEN: AqWRU0wOROexWLxTuwk8zAl4kMkgGZwVFQRmBTDB7SvorjohtWfYOPJx+8HlwyhjIqdJ5B7CDIR5jkAZRBc91XQK7J4zh6ahsLKvqnBObYR5lylHVR6CBQNb/mATQE4qXbHI+fwwHdZn221TkNBzFULMs8S9GlTeRZ3HlufN+0tzUMzZyyYvv/oQdtbF42JGFfgVrvknvz6wbUBrKwlvDqRMRnDE5lB4+D2n2xrdYyBLz+gJgyU5hUHnHVBWWo55itgx/do+TiDlA9u9blbj7BqVNyTwG/BkAnBDtJzJfrZbIhb6o21c3hpRJhMsKne2Tdof5ur+l7NcV0r1jnu/HeAczS9bJOCtUygUmKnrEPZjkIYbXI/mM65DiOFcJWtelSgn7WMh4kAV+Uh6CqaokpeY9sv9nbHYS0VLok2e2LPzgw2m27J0LboW9lhLby0vgIaVtqCLCtkOCe9zX65m6mvBCteHQGXvjy/tcbNRlsHtF3dENVdDtRHMETHKNmvVpEcEklyawz0kKtnXWREgxKR0k/s7ISZhKJaWW3zKVKIVBfYMJUbe6hotU3Zyi62ctNfolZTdnjpOO441eXHM6giMEm7ioF4vt7w6geZeOFaIlRm3uVFfbdFO+cr+5ZmjOZZDwz7s458dCfZlVmfpA09YXMaads67AcE/62mzdxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
